spring:
  application:
    name: guestbook
  datasource:
    #    profileSQL=true: Driver ?? ???? ??? ?????.
    #    logger=Slf4JLogger: Driver ?? ?? ??? ??? ??? ?????.
    #    MySQL ????: ???? System.err ? ????? ???? ?? ??? ??? ??? ?? ???.
    #    MariaDB ????: Slf4j ? ???? ??? ???? ??? ??? ??? ????.
    #    maxQuerySizeToLog=999999: ??? ?? ??
    url: jdbc:mysql://localhost:3306/guestbook?profileSQL=true&logger=Slf4JLogger&useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&maxQuerySizeToLog=999999
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    hikari:
      connection-timeout: 300000
  jpa:
    hibernate:
      #?????? ?? ??? ? ???? ?? ??
      ddl-auto: update
    properties:
      hibernate:
        jdbc:

        # show_sql: true
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
  batch:
    jdbc:
      initialize-schema: ALWAYS
